complete -c bitty -l width -r -d 'World width'
complete -c bitty -l height -r -d 'World height'
complete -c bitty -l density -r -d 'Initial live-cell density'
complete -c bitty -l speed -r -d 'Generations per second'
complete -c bitty -l seed -r -d 'Random seed'
complete -c bitty -l wrap -r -a 'true false' -d 'Connect opposite edges'
complete -c bitty -l paused -d 'Start paused'
complete -c bitty -l intro -d 'Play startup intro'
complete -c bitty -l no-intro -d 'Skip startup intro'
complete -c bitty -l no-color -d 'Disable color'
complete -c bitty -l theme-file -r -F -d 'Portable theme file'
complete -c bitty -l version -d 'Print version'
